# Generated by Django 3.0.5 on 2020-04-29 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bezel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'bezels',
            },
        ),
        migrations.CreateModel(
            name='BezelFind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=1000)),
            ],
            options={
                'db_table': 'bezels_finds',
            },
        ),
        migrations.CreateModel(
            name='Bracelet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'bracelets',
            },
        ),
        migrations.CreateModel(
            name='BraceletFind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=1000)),
            ],
            options={
                'db_table': 'bracelets_finds',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'collections',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_oyster', models.BooleanField()),
                ('price', models.IntegerField()),
                ('bezel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Bezel')),
                ('bracelet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Bracelet')),
            ],
            options={
                'db_table': 'details',
            },
        ),
        migrations.CreateModel(
            name='Dial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'dials',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_url', models.URLField(max_length=1000)),
                ('background_url', models.URLField(max_length=1000)),
            ],
            options={
                'db_table': 'materials',
            },
        ),
        migrations.CreateModel(
            name='MiddleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_url', models.URLField(max_length=1000)),
                ('image_url', models.URLField(max_length=1000)),
                ('title', models.CharField(max_length=50)),
                ('sub_title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'middle_images',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter', models.IntegerField()),
            ],
            options={
                'db_table': 'sizes',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_watch', models.URLField(max_length=1000)),
                ('header_background', models.URLField(max_length=1000)),
                ('description', models.CharField(max_length=500)),
                ('sub_description', models.CharField(max_length=500)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Category')),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Collection')),
                ('detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Detail')),
                ('middle_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.MiddleImage')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('sub_title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('thumbnail_url', models.URLField(max_length=1000)),
                ('image_url', models.URLField(max_length=1000)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product')),
            ],
            options={
                'db_table': 'features',
            },
        ),
        migrations.CreateModel(
            name='DialFind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=1000)),
                ('dial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Dial')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Material')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Size')),
            ],
            options={
                'db_table': 'dials_finds',
            },
        ),
        migrations.AddField(
            model_name='detail',
            name='dial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Dial'),
        ),
        migrations.AddField(
            model_name='detail',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Material'),
        ),
        migrations.AddField(
            model_name='detail',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Size'),
        ),
        migrations.CreateModel(
            name='ConfigureWatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Bezel')),
                ('bracelet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Bracelet')),
                ('dial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Dial')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Material')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Size')),
            ],
            options={
                'db_table': 'configure_watches',
            },
        ),
    ]
