# Generated by Django 3.0.5 on 2020-04-27 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='color',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='size',
            new_name='diameter',
        ),
    ]
