# Generated by Django 3.0.5 on 2020-04-27 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200427_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bezel',
            name='bezel_find',
        ),
        migrations.RemoveField(
            model_name='bracelet',
            name='bracelet_find',
        ),
        migrations.RemoveField(
            model_name='dial',
            name='dial_find',
        ),
        migrations.AddField(
            model_name='bezelfind',
            name='bezel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Bezel'),
        ),
        migrations.AddField(
            model_name='braceletfind',
            name='bracelet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Bracelet'),
        ),
        migrations.AddField(
            model_name='dialfind',
            name='dial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Dial'),
        ),
    ]
