# Generated by Django 3.0.5 on 2020-04-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200428_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='middleimage',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
