# Generated by Django 3.0.5 on 2020-04-28 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product')),
            ],
            options={
                'db_table': 'likes',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=200)),
                ('bezel', models.ManyToManyField(through='product.ConfigureWatch', to='product.Bezel')),
                ('bracelet', models.ManyToManyField(through='product.ConfigureWatch', to='product.Bracelet')),
                ('dial', models.ManyToManyField(through='product.ConfigureWatch', to='product.Dial')),
                ('liked_product', models.ManyToManyField(through='user.Like', to='product.Product')),
                ('material', models.ManyToManyField(through='product.ConfigureWatch', to='product.Material')),
                ('size', models.ManyToManyField(through='product.ConfigureWatch', to='product.Size')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User'),
        ),
    ]
